#!/usr/bin/env node
// Smoke test for the one published npm package, paseo-bm-plugin (Technical
// Design §11, the packed-package layer; ADR-009, ADR-022 decision 1).
//
// Everything here runs against the real tarball `npm pack` makes from
// plugin-package/ (ADR-026), never against the source tree: the failure this
// guards against is a tarball that differs from what the repository checks,
// which only shows once the version is on npm — and a version on npm cannot be
// republished.
//
// It packs plugin-package/ as it is, exactly as release.yml's publish step does
// (the package has no `prepack`). plugin-package/ is generated by `npm run
// build`; run it first after any change to plugin/ or to the version, as
// release.yml does, otherwise the checks below fail.
//
// Steps:
//   1. The root package.json is private and declares nothing a publish would
//      use (no `bin`, `files` or `prepack`): the repository ships one package.
//   2. plugin-package/ is what a fresh build writes from plugin/, then `npm
//      pack` it into an empty temp directory.
//   3. Extract the tarball and assert its contents: its root is a loadable
//      plugin (manifest requiring Paseo >=0.9.0, both entries, LICENSE,
//      README.md) and holds nothing else; the two entries stay within
//      paseo.cafe's 2,000,000-byte scan budget; the version is the root
//      package.json's; no install lifecycle scripts; no dependencies.
//   4. Install the tarball into an isolated temp project, offline, with a
//      throwaway npm cache and userconfig (the package has no dependencies, so
//      nothing needs the network); assert the installed package is the packed
//      plugin and that the install wrote nothing outside node_modules/.
//
// Flags: --keep  leave the temp directory in place for inspection.

import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = fileURLToPath(new URL("..", import.meta.url));
const keep = process.argv.includes("--keep");
const failures = [];

function check(condition, message) {
  if (condition) {
    console.log(`ok   ${message}`);
  } else {
    console.log(`FAIL ${message}`);
    failures.push(message);
  }
}

function run(command, args, options = {}) {
  const result = spawnSync(command, args, { encoding: "utf8", ...options });
  if (result.error) throw result.error;
  return result;
}

function mustRun(label, command, args, options = {}) {
  const result = run(command, args, { stdio: ["ignore", "pipe", "pipe"], ...options });
  if (result.status !== 0) {
    console.error(result.stdout);
    console.error(result.stderr);
    throw new Error(`${label} failed with exit code ${result.status}`);
  }
  return result;
}

/** Map of POSIX-relative path -> sha256 for every file under `root`. */
function snapshot(root) {
  const out = new Map();
  const walk = (dir, prefix) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const abs = join(dir, entry.name);
      const rel = prefix ? `${prefix}/${entry.name}` : entry.name;
      if (entry.isDirectory()) walk(abs, rel);
      else if (entry.isFile()) out.set(rel, createHash("sha256").update(readFileSync(abs)).digest("hex"));
      else out.set(rel, `<${entry.isSymbolicLink() ? "symlink" : "special"}>`);
    }
  };
  if (existsSync(root)) walk(root, "");
  return out;
}

function sameSnapshot(a, b) {
  if (a.size !== b.size) return false;
  for (const [key, value] of a) if (b.get(key) !== value) return false;
  return true;
}

const work = mkdtempSync(join(tmpdir(), "paseo-bm-smoke-"));
const packDir = join(work, "pack");
const extractDir = join(work, "extract");
const projectDir = join(work, "project");
const npmCache = join(work, "npm-cache");
const npmUserconfig = join(work, "npmrc");
for (const dir of [packDir, extractDir, projectDir, npmCache]) {
  mkdirSync(dir, { recursive: true });
}
writeFileSync(npmUserconfig, "");

const npmEnv = {
  ...process.env,
  npm_config_cache: npmCache,
  npm_config_userconfig: npmUserconfig,
  npm_config_audit: "false",
  npm_config_fund: "false",
  npm_config_update_notifier: "false",
};

try {
  const rootManifest = JSON.parse(readFileSync(join(repoRoot, "package.json"), "utf8"));
  const expectedVersion = rootManifest.version;
  if (typeof expectedVersion !== "string" || expectedVersion.length === 0) {
    throw new Error('package.json is missing a usable "version" field');
  }
  console.log(`paseo-bm-plugin smoke (packed) — expecting version ${expectedVersion}`);
  console.log(`work dir: ${work}`);

  // 1. The repository publishes one package. The root package.json is the
  // version source and the development root, never a package (ADR-022 D1).
  console.log("\n# root package.json");
  check(rootManifest.private === true, 'root package.json is "private": true');
  const publishFields = ["bin", "files"].filter((field) => field in rootManifest);
  check(publishFields.length === 0, `root package.json declares no bin or files${publishFields.length ? ` (found: ${publishFields.join(", ")})` : ""}`);
  check(!("prepack" in (rootManifest.scripts ?? {})), "root package.json has no prepack script");

  // 2. Pack plugin-package/ the way release.yml publishes it, once it is known to be current.
  console.log("\n# plugin-package/ is current");
  const current = run(process.execPath, [join(repoRoot, "scripts", "generate-plugin-package.mjs"), "--check"], { stdio: ["ignore", "pipe", "pipe"] });
  check(current.status === 0, `plugin-package/ is what \`npm run build\` writes${current.status === 0 ? "" : ` (${current.stderr.trim()})`}`);
  console.log("\n# npm pack plugin-package/");
  const pack = run("npm", ["pack", "--pack-destination", packDir], {
    cwd: join(repoRoot, "plugin-package"),
    env: npmEnv,
    stdio: ["ignore", "pipe", "inherit"],
  });
  process.stdout.write(pack.stdout);
  if (pack.status !== 0) throw new Error(`npm pack failed with exit code ${pack.status}`);
  const tarballs = readdirSync(packDir).filter((name) => name.endsWith(".tgz"));
  if (tarballs.length !== 1) throw new Error(`expected exactly one tarball, found: ${tarballs.join(", ") || "none"}`);
  const tarball = join(packDir, tarballs[0]);

  // 3. Inspect the tarball itself, independently of what npm reported. Its root
  // must BE a loadable plugin: that is what the paseo.cafe security scan
  // checks, and it always reads the tarball root (ADR-009).
  console.log("\n# tarball contents");
  mustRun("tar extract", "tar", ["-xzf", tarball, "-C", extractDir]);
  const packed = join(extractDir, "package");
  const packedManifest = JSON.parse(readFileSync(join(packed, "package.json"), "utf8"));
  check(packedManifest.name === "paseo-bm-plugin", "package is named paseo-bm-plugin");
  check(packedManifest.version === expectedVersion, `package version is ${expectedVersion}`);
  for (const entry of ["paseo-plugin.json", "index.client.tsx", "index.server.ts", "LICENSE", "README.md"]) {
    check(existsSync(join(packed, entry)), `tarball root has ${entry}`);
  }
  // The manifest a daemon reads out of the tarball is what decides whether it
  // loads at all; 0.8 has no npm plugin source, so it must refuse (ADR-012 D2).
  const pluginManifest = JSON.parse(readFileSync(join(packed, "paseo-plugin.json"), "utf8"));
  check(pluginManifest.requirements?.paseo === ">=0.9.0", 'manifest requires Paseo ">=0.9.0"');
  check(!existsSync(join(packed, "images")), "tarball carries no images/ directory");
  // The tarball is exactly the published package: the bundled entries, the
  // manifest, package.json, LICENSE and README.md, each the file in plugin-package/.
  const packedFiles = snapshot(packed);
  const expectedFiles = ["LICENSE", "README.md", "index.client.tsx", "index.server.ts", "package.json", "paseo-plugin.json"];
  check(
    JSON.stringify([...packedFiles.keys()].sort()) === JSON.stringify(expectedFiles),
    `tarball holds exactly ${expectedFiles.join(", ")} (found: ${[...packedFiles.keys()].sort().join(", ")})`,
  );
  const repoFiles = snapshot(join(repoRoot, "plugin-package"));
  const differing = expectedFiles.filter((path) => path !== "package.json" && repoFiles.get(path) !== packedFiles.get(path));
  check(differing.length === 0, `each packed file is the one in plugin-package/${differing.length ? ` (differs: ${differing.join(", ")})` : ""}`);
  // paseo.cafe's security scan refuses a reachable graph over 2,000,000 bytes (ADR-026).
  const entryBytes = ["index.server.ts", "index.client.tsx"].reduce((sum, name) => sum + readFileSync(join(packed, name)).length, 0);
  check(entryBytes <= 2_000_000, `the two entries are ${entryBytes} bytes, within paseo.cafe's 2,000,000-byte scan budget`);
  // Downloading the package must never run code on the installing machine
  // (AGENTS.md, hard packaging rule).
  const lifecycle = ["preinstall", "install", "postinstall", "prepare"].filter(
    (name) => name in (packedManifest.scripts ?? {}),
  );
  check(lifecycle.length === 0, `package.json has no install lifecycle scripts${lifecycle.length ? ` (found: ${lifecycle.join(", ")})` : ""}`);
  check(
    Object.keys(packedManifest.dependencies ?? {}).length === 0,
    "package.json has no runtime dependencies (offline install possible)",
  );

  // 4. Install the tarball into an isolated project, offline.
  console.log("\n# npm install <tarball> (offline, isolated cache)");
  writeFileSync(join(projectDir, "package.json"), JSON.stringify({ name: "smoke-project", private: true }, null, 2));
  const outsideNodeModules = () =>
    new Map([...snapshot(projectDir)].filter(([path]) => path !== "node_modules" && !path.startsWith("node_modules/")));
  const projectBefore = outsideNodeModules();
  mustRun("npm install", "npm", ["install", "--offline", "--no-save", "--no-package-lock", tarball], {
    cwd: projectDir,
    env: npmEnv,
  });
  const installed = join(projectDir, "node_modules", "paseo-bm-plugin");
  check(existsSync(join(installed, "paseo-plugin.json")), "installed package has paseo-plugin.json at its root");
  // npm may normalise the installed package.json; every other file must be
  // the packed file, byte for byte.
  const withoutManifest = (files) => new Map([...files].filter(([path]) => path !== "package.json"));
  check(
    sameSnapshot(withoutManifest(packedFiles), withoutManifest(snapshot(installed))),
    "installed package holds exactly the packed files",
  );
  check(sameSnapshot(projectBefore, outsideNodeModules()), "the install wrote nothing outside node_modules/");
} catch (error) {
  failures.push(error instanceof Error ? error.message : String(error));
  console.error(`FAIL ${error instanceof Error ? error.message : String(error)}`);
} finally {
  if (keep) console.log(`\nkept work dir: ${work}`);
  else rmSync(work, { recursive: true, force: true });
}

if (failures.length > 0) {
  console.error(`\nsmoke (packed): ${failures.length} failure(s)`);
  process.exit(1);
}
console.log("\nsmoke (packed): all checks passed");
